# This workflow will deploy a project to an environment using Github Actions

name: Continuous Deployment Steps

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_WEBAPP_NAME:
        required: true
      AZURE_RESOURCEGROUP_NAME:
        required: true
jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: GithubActionCICD
          path: artifacts/
     
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to ${{ inputs.env }}
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }} 
          slot-name: deployment-slot
          package: artifacts/

      - name: Swap slots
       run: |
         az webapp deployment slot swap --resource-group ${{ secrets.AZURE_RESOURCEGROUP_NAME }} --name ${{ secrets.AZURE_WEBAPP_NAME }} --slot deployment-slot --target-slot production --verbose