# This workflow will build and deploy .NET project

name: Continuous Integration and Deployment

on:
  push: 
   branches: [ "main" ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Dotnet restore
      run: dotnet restore

    - name: Dotnet build
      run: dotnet build --configuration Release --no-restore

    - name: Dotnet format
      run: dotnet format --verbosity detailed --verify-no-changes 

    - name: Dotnet test
      run: dotnet test --configuration Release --no-build --verbosity detailed

    - name: Publish
      run: dotnet publish --configuration Release --output artifacts
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GithubActionCICD
        path: artifacts/
  
  deploy_dev:
    name: Deploy to dev
    needs: build
    uses: ./.github/workflows/cd-steps.yml
    with: 
      env: dev
    secrets: inherit

  deploy_prod:
    name: Deploy to prod
    needs: deploy_dev
    uses: ./.github/workflows/cd-steps.yml
    with:
      env: prod
    secrets: inherit